export const NET_TO_GROSS_BASIC_PROPORTION = 1.075
export const BASIC_SIMULATION_YEARS = 40
export const BASIC_SIMULATION_YEARS_OF_RETIREMENTS = 20
export const BASIC_SIMULATION_FOUND = 'B'
export const BASIC_SIMULATION_STATING_MONTH = 11
export const BASIC_SIMULATION_STARTING_YEAR = 2019
