name: Scrap Superintencia

on:
  schedule:
    - cron: '0 13 * * *'
    - cron: '0 10 * * *'
    - cron: '0 8 * * *'
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Run script
      run: node cron/index.js
